CREATE TABLE IF NOT EXISTS organization
(
    id          int4 generated by default as identity,
    name        VARCHAR(255) NOT NULL,
    fizaddres   VARCHAR(255),
    legaladdres VARCHAR(255),
    director_id int4,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS subdivision
(
    id              int4 generated by default as identity,
    name            VARCHAR(255) NOT NULL,
    contactdetails  VARCHAR(255),
    director_id     int4,
    organization_id int4,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS employee
(
    id            int4 generated by default as identity,
    name          VARCHAR(255) NOT NULL,
    surname       VARCHAR(255) NOT NULL,
    patronymic    VARCHAR(255),
    post          VARCHAR(255),
    subdivision_id int4,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS task
(
    id              int4 generated by default as identity,
    subjectorder    VARCHAR(255),
    author_id       int4,
    deadline        DATE,
    singofcontrol   BOOLEAN,
    singofexecution BOOLEAN,
    text            TEXT,
    status          VARCHAR(255) NOT NULL,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS employee_task
(
    employee_id int4 not null,
    task_id     int4 not null,
    constraint employee_task_pk primary key (employee_id, task_id),
    constraint employee_task_fk_task foreign key (task_id) references task,
    constraint employee_task_fk_employee foreign key (employee_id) references employee
);

alter table if exists subdivision
    add constraint subdivision_employee_fk foreign key (director_id) references employee on DELETE set null;

alter table if exists subdivision
    add constraint subdivision_organization_fk foreign key (organization_id) references organization on DELETE set null;

alter table if exists employee
    add constraint employee_subdivision_fk foreign key (subdivision_id) references subdivision on DELETE set null;

alter table if exists task
    add constraint task_employee_fk foreign key (author_id) references employee on DELETE set null;

alter table if exists organization
    add constraint organization_employee_fk foreign key (director_id) references employee on DELETE set null;